#!/bin/bash
set -e

# Initialize default snap configuration values on first install
if [ -z "$(snapctl get driver)" ]; then
    snapctl set driver=vm
fi

if [ -z "$(snapctl get socket-mode)" ]; then
    snapctl set socket-mode=0660
fi
